services:
  app:
    image: ghcr.io/github-username/nextjs-app:latest  # GitHub Actions에서 푸시된 Docker 이미지
    container_name: nextjs-app
    restart: unless-stopped
    ports:
      - "3000:3000"  # Next.js 애플리케이션 포트
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"  # Nginx가 80번 포트에서 요청을 받음
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx 설정 파일
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
